---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Viral Tool"
keywords:    "viral tool, malware generator, virus generator, virus maker, virus creator, malware creator, malik usman aura, leo softwares pakistan, viraltool"
description: "A smart, fast and secure malware generator for security testing purposes"
source_link: "https://github.com/usmanaura47/viral-tool-site"
favicon:     "/images/favicon.ico"
touch_icon:  "/images/apple-touch-icon.png"
show_downloads: true
google_analytics:
theme: hacker-theme

twitter:
  username: malikusmanaura
  image: /images/logo.png

url: https://viraltool.tk   # with the https protocol
enforce_ssl: viraltool.tk

logo: /images/logo.png

image: 
  path: /images/logo.png

author: "Malik Usman Aura"
social:
  name: Malik Usman Aura
  links:
    - https://twitter.com/malikusmanaura
    - https://www.facebook.com/malikusman.aura
    - https://pk.linkedin.com/in/malikusmanaura
    - https://plus.google.com/+MalikUsmanAura
    - https://github.com/usmanaura47
    - https://sourceforge.net/u/usman47
    
download: viraltool.zip
downloadc: viraltoolcli.zip
sourcecode: https://github.com/usmanaura47/viral-tool

gems:
  - jekyll-sitemap
  - jekyll-seo-tag